name: simple_mention
description: This is simple mention package.
version: 0.0.1
repository: https://github.com/arcanine33/simple_mention
issue_tracker: https://github.com/arcanine33/simple_mention/issues

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

                    
                                      